[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./" }]

# Bật optimizer và viaIR để fix lỗi Stack too deep
optimizer = true
optimizer_runs = 200
via_ir = true

[app]
name = "sim_puller_test"
